// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/activity/ActivityMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto3 {

  /// <summary>Holder for reflection information generated from proto/activity/ActivityMessage.proto</summary>
  public static partial class ActivityMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/activity/ActivityMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActivityMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRwcm90by9hY3Rpdml0eS9BY3Rpdml0eU1lc3NhZ2UucHJvdG8aIHByb3Rv",
            "L2NvbW1vbi9Db21tb25NZXNzYWdlLnByb3RvIooBChhTZXZlbkRheUdpZnRJ",
            "bmZvUmVzcG9uc2USDgoGdXNlcklEGAEgASgDEhIKClNldmVuR2lmdDEYAiAB",
            "KAgSEgoKU2V2ZW5HaWZ0MhgDIAEoCBIQCghMb2dpbkRheRgEIAEoBRIPCgdF",
            "bmRUaW1lGAUgASgDEhMKC3JlY2VpdmVkSWRzGAYgAygFIjgKGlNldmVuRGF5",
            "R2lmdFJlY2VpdmVSZXF1ZXN0Eg4KBnVzZXJJRBgBIAEoAxIKCgJpZBgCIAEo",
            "BSJVChtTZXZlbkRheUdpZnRSZWNlaXZlUmVzcG9uc2USDgoGdXNlcklEGAEg",
            "ASgDEgoKAmlkGAIgASgFEhoKB3Jld2FyZHMYAyADKAsyCS5LZXlWYWx1ZUIn",
            "Chxjb20udG9wZ2FtZS5tZXNzYWdlLmFjdGl2aXR5qgIGUHJvdG8zYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto3.CommonMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto3.SevenDayGiftInfoResponse), global::Proto3.SevenDayGiftInfoResponse.Parser, new[]{ "UserID", "SevenGift1", "SevenGift2", "LoginDay", "EndTime", "ReceivedIds" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto3.SevenDayGiftReceiveRequest), global::Proto3.SevenDayGiftReceiveRequest.Parser, new[]{ "UserID", "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto3.SevenDayGiftReceiveResponse), global::Proto3.SevenDayGiftReceiveResponse.Parser, new[]{ "UserID", "Id", "Rewards" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SevenDayGiftInfoResponse : pb::IMessage<SevenDayGiftInfoResponse> {
    private static readonly pb::MessageParser<SevenDayGiftInfoResponse> _parser = new pb::MessageParser<SevenDayGiftInfoResponse>(() => new SevenDayGiftInfoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SevenDayGiftInfoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto3.ActivityMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftInfoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftInfoResponse(SevenDayGiftInfoResponse other) : this() {
      userID_ = other.userID_;
      sevenGift1_ = other.sevenGift1_;
      sevenGift2_ = other.sevenGift2_;
      loginDay_ = other.loginDay_;
      endTime_ = other.endTime_;
      receivedIds_ = other.receivedIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftInfoResponse Clone() {
      return new SevenDayGiftInfoResponse(this);
    }

    /// <summary>Field number for the "userID" field.</summary>
    public const int UserIDFieldNumber = 1;
    private long userID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UserID {
      get { return userID_; }
      set {
        userID_ = value;
      }
    }

    /// <summary>Field number for the "SevenGift1" field.</summary>
    public const int SevenGift1FieldNumber = 2;
    private bool sevenGift1_;
    /// <summary>
    ///七日礼包第一档购买标记
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SevenGift1 {
      get { return sevenGift1_; }
      set {
        sevenGift1_ = value;
      }
    }

    /// <summary>Field number for the "SevenGift2" field.</summary>
    public const int SevenGift2FieldNumber = 3;
    private bool sevenGift2_;
    /// <summary>
    ///七日礼包第二档购买标记
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SevenGift2 {
      get { return sevenGift2_; }
      set {
        sevenGift2_ = value;
      }
    }

    /// <summary>Field number for the "LoginDay" field.</summary>
    public const int LoginDayFieldNumber = 4;
    private int loginDay_;
    /// <summary>
    ///登陆天数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LoginDay {
      get { return loginDay_; }
      set {
        loginDay_ = value;
      }
    }

    /// <summary>Field number for the "EndTime" field.</summary>
    public const int EndTimeFieldNumber = 5;
    private long endTime_;
    /// <summary>
    ///结束时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "receivedIds" field.</summary>
    public const int ReceivedIdsFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_receivedIds_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> receivedIds_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///七日礼包领取id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> ReceivedIds {
      get { return receivedIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SevenDayGiftInfoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SevenDayGiftInfoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserID != other.UserID) return false;
      if (SevenGift1 != other.SevenGift1) return false;
      if (SevenGift2 != other.SevenGift2) return false;
      if (LoginDay != other.LoginDay) return false;
      if (EndTime != other.EndTime) return false;
      if(!receivedIds_.Equals(other.receivedIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserID != 0L) hash ^= UserID.GetHashCode();
      if (SevenGift1 != false) hash ^= SevenGift1.GetHashCode();
      if (SevenGift2 != false) hash ^= SevenGift2.GetHashCode();
      if (LoginDay != 0) hash ^= LoginDay.GetHashCode();
      if (EndTime != 0L) hash ^= EndTime.GetHashCode();
      hash ^= receivedIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserID);
      }
      if (SevenGift1 != false) {
        output.WriteRawTag(16);
        output.WriteBool(SevenGift1);
      }
      if (SevenGift2 != false) {
        output.WriteRawTag(24);
        output.WriteBool(SevenGift2);
      }
      if (LoginDay != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(LoginDay);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(EndTime);
      }
      receivedIds_.WriteTo(output, _repeated_receivedIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserID);
      }
      if (SevenGift1 != false) {
        size += 1 + 1;
      }
      if (SevenGift2 != false) {
        size += 1 + 1;
      }
      if (LoginDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LoginDay);
      }
      if (EndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTime);
      }
      size += receivedIds_.CalculateSize(_repeated_receivedIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SevenDayGiftInfoResponse other) {
      if (other == null) {
        return;
      }
      if (other.UserID != 0L) {
        UserID = other.UserID;
      }
      if (other.SevenGift1 != false) {
        SevenGift1 = other.SevenGift1;
      }
      if (other.SevenGift2 != false) {
        SevenGift2 = other.SevenGift2;
      }
      if (other.LoginDay != 0) {
        LoginDay = other.LoginDay;
      }
      if (other.EndTime != 0L) {
        EndTime = other.EndTime;
      }
      receivedIds_.Add(other.receivedIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserID = input.ReadInt64();
            break;
          }
          case 16: {
            SevenGift1 = input.ReadBool();
            break;
          }
          case 24: {
            SevenGift2 = input.ReadBool();
            break;
          }
          case 32: {
            LoginDay = input.ReadInt32();
            break;
          }
          case 40: {
            EndTime = input.ReadInt64();
            break;
          }
          case 50:
          case 48: {
            receivedIds_.AddEntriesFrom(input, _repeated_receivedIds_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SevenDayGiftReceiveRequest : pb::IMessage<SevenDayGiftReceiveRequest> {
    private static readonly pb::MessageParser<SevenDayGiftReceiveRequest> _parser = new pb::MessageParser<SevenDayGiftReceiveRequest>(() => new SevenDayGiftReceiveRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SevenDayGiftReceiveRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto3.ActivityMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftReceiveRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftReceiveRequest(SevenDayGiftReceiveRequest other) : this() {
      userID_ = other.userID_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftReceiveRequest Clone() {
      return new SevenDayGiftReceiveRequest(this);
    }

    /// <summary>Field number for the "userID" field.</summary>
    public const int UserIDFieldNumber = 1;
    private long userID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UserID {
      get { return userID_; }
      set {
        userID_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SevenDayGiftReceiveRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SevenDayGiftReceiveRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserID != other.UserID) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserID != 0L) hash ^= UserID.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserID);
      }
      if (Id != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserID);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SevenDayGiftReceiveRequest other) {
      if (other == null) {
        return;
      }
      if (other.UserID != 0L) {
        UserID = other.UserID;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserID = input.ReadInt64();
            break;
          }
          case 16: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SevenDayGiftReceiveResponse : pb::IMessage<SevenDayGiftReceiveResponse> {
    private static readonly pb::MessageParser<SevenDayGiftReceiveResponse> _parser = new pb::MessageParser<SevenDayGiftReceiveResponse>(() => new SevenDayGiftReceiveResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SevenDayGiftReceiveResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto3.ActivityMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftReceiveResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftReceiveResponse(SevenDayGiftReceiveResponse other) : this() {
      userID_ = other.userID_;
      id_ = other.id_;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SevenDayGiftReceiveResponse Clone() {
      return new SevenDayGiftReceiveResponse(this);
    }

    /// <summary>Field number for the "userID" field.</summary>
    public const int UserIDFieldNumber = 1;
    private long userID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UserID {
      get { return userID_; }
      set {
        userID_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Proto3.KeyValue> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(26, global::Proto3.KeyValue.Parser);
    private readonly pbc::RepeatedField<global::Proto3.KeyValue> rewards_ = new pbc::RepeatedField<global::Proto3.KeyValue>();
    /// <summary>
    ///奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Proto3.KeyValue> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SevenDayGiftReceiveResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SevenDayGiftReceiveResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserID != other.UserID) return false;
      if (Id != other.Id) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserID != 0L) hash ^= UserID.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserID);
      }
      if (Id != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Id);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserID);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SevenDayGiftReceiveResponse other) {
      if (other == null) {
        return;
      }
      if (other.UserID != 0L) {
        UserID = other.UserID;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserID = input.ReadInt64();
            break;
          }
          case 16: {
            Id = input.ReadInt32();
            break;
          }
          case 26: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
