// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/Mid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto3 {

  /// <summary>Holder for reflection information generated from proto/Mid.proto</summary>
  public static partial class MidReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/Mid.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MidReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wcm90by9NaWQucHJvdG8q/hgKA01JRBIICgROT05FEAASFQoRU2VydmVy",
            "UmVnaXN0ZXJSZXEQZRIVChFTZXJ2ZXJSZWdpc3RlclJlcxBmEhEKDVNlcnZl",
            "ckxpc3RSZXEQZxIRCg1TZXJ2ZXJMaXN0UmVzEGgSFwoTQ2hhbmdlUm9sZVNl",
            "cnZlclJlcRBpEhcKE0NoYW5nZVJvbGVTZXJ2ZXJSZXMQahISCg5TZXJ2ZXJF",
            "dmVudFJlcRBrEhIKDlNlcnZlckV2ZW50UmVzEGwSEwoPU2VydmVyU3RhdHVz",
            "UmVzEG0SEAoMU2VydmVyQ21kUmVxEG4SFwoTTGlua1NlcnZlckNoYW5nZVJl",
            "cxBvEgwKCFdlYkdtUmVxEHASDAoIV2ViR21SZXMQcRITCg9XZWJUb2dnbGVI",
            "b3RSZXEQchIUChBXZWJTZW5kTm90aWNlUmVxEHMSFwoSU2VydmVyTG9naW5M",
            "aXN0UmVxEMgBEhcKElNlcnZlckxvZ2luTGlzdFJlcxDJARITCg5TeXN0ZW1F",
            "cnJvclJlcxCRAxIPCgpDb21tYW5kUmVxEPUDEhEKDEZsYWdEaXJ0eVJlcxDZ",
            "BBITCg5OZXdEYXlEaXJ0eVJlcRDaBBITCg5OZXdEYXlEaXJ0eVJlcxDbBBIR",
            "CgxMb2dBY3Rpb25SZXEQvAUSFgoRTG9nQWN0aW9uQmF0Y2hSZXEQvQUSDwoK",
            "S2lja091dFJlcxCQThINCghMb2dpblJlcRCRThINCghMb2dpblJlcxCSThIN",
            "CghIZWFydFJlcRCbThINCghIZWFydFJlcxCcThIQCgtLaWxsVXNlclJlcxCd",
            "ThITCg5NZXNzYWdlU2VlZFJlcxCeThITCg5Mb2dpbkZpbmlzaFJlcxCfThIO",
            "CglMb2dvdXRSZXEQoE4SDgoJTG9nb3V0UmVzEKFOEhMKDkxvZ2luVmVyaWZ5",
            "UmVxEKJOEhMKDkxvZ2luVmVyaWZ5UmVzEKNOEhQKD1VzZXJCYXNlSW5mb1Jl",
            "cxCkThIRCgxHdWlkZVNhdmVSZXEQpU4SEQoMR3VpZGVJbmZvUmVzEKZOEhMK",
            "DlBheU9yZGVyR2VuUmVxEPROEhMKDlBheU9yZGVyR2VuUmVzEPVOEhQKD1Bh",
            "eVNka0FjdGlvblJlcRD2ThIUCg9QYXlTZGtBY3Rpb25SZXMQ904SFgoRUGF5",
            "U2RrQ2FsbGJhY2tSZXMQ+E4SEwoNRW50ZXJMZXZlbFJlcRChnAESEwoNRW50",
            "ZXJMZXZlbFJlcxCinAESEgoMRXhpdExldmVsUmVxEKucARISCgxFeGl0TGV2",
            "ZWxSZXMQrJwBEhMKDVN0YXJ0TGV2ZWxSZXEQrZwBEhMKDVN0YXJ0TGV2ZWxS",
            "ZXMQrpwBEhUKD1Jldml2ZVBsYXllclJlcRCvnAESFQoPUmV2aXZlUGxheWVy",
            "UmVzELCcARITCg1DaGFsbGVuZ2VzUmVzELGcARIYChJDaGFsbGVuZ2VzRGly",
            "dHlSZXMQspwBEhsKFUFkZENoYWxsZW5nZXNMZXZlbFJlcxCznAESFAoOQWNo",
            "aWV2ZUluZm9SZXMQiKQBEhUKD0FjaGlldmVEaXJ0eVJlcxCJpAESFgoQQWNo",
            "aWV2ZVJld2FyZFJlcRCKpAESFgoQQWNoaWV2ZVJld2FyZFJlcxCLpAESEQoL",
            "UmFua0luZm9SZXEQ8KsBEhEKC1JhbmtJbmZvUmVzEPGrARIRCgtSYW5rVXNl",
            "clJlcRDyqwESEQoLUmFua1VzZXJSZXMQ86sBEhIKDERpcnR5UmFua1JlcxD0",
            "qwESEwoNUmFua1Jld2FyZFJlcRD1qwESEwoNUmFua1Jld2FyZFJlcxD2qwES",
            "EQoLSGVyb0luZm9SZXMQ2LMBEhgKEkhlcm9GaWdodENoYW5nZVJlcRDZswES",
            "GAoSSGVyb0ZpZ2h0Q2hhbmdlUmVzENqzARIQCgpIZXJvQnV5UmVxENuzARIQ",
            "CgpIZXJvQnV5UmVzENyzARISCgxIZXJvRXF1aXBSZXEQ3bMBEhIKDEhlcm9F",
            "cXVpcFJlcxDeswESEgoMSGVyb0RpcnR5UmVzEN+zARITCg1FcXVpcEluZm9z",
            "UmVzEOCzARITCg1FcXVpcERpcnR5UmVxEOGzARITCg1FcXVpcERpcnR5UmVz",
            "EOKzARIYChJIZXJvRXF1aXBVbmxvY2tSZXEQ47MBEhgKEkhlcm9FcXVpcFVu",
            "bG9ja1JlcxDkswESGQoTSGVyb0VxdWlwVXBncmFkZVJlcRDlswESGQoTSGVy",
            "b0VxdWlwVXBncmFkZVJlcxDmswESEgoMSXRlbUluZm9zUmVzELy0ARISCgxJ",
            "dGVtRGlydHlSZXEQvbQBEhIKDEl0ZW1EaXJ0eVJlcxC+tAESEgoMT3BlbkNo",
            "ZXN0UmVxEL+0ARISCgxPcGVuQ2hlc3RSZXMQwLQBEhcKEUJ1eUFjdGlvblBv",
            "aW50UmVxEMG0ARIXChFCdXlBY3Rpb25Qb2ludFJlcxDCtAESDwoJU2lnbklu",
            "UmVxEKC1ARIPCglTaWduSW5SZXMQobUBEhEKC1Nob3BJbmZvUmVxEIW2ARIR",
            "CgtTaG9wSW5mb1JlcxCGtgESEgoMU2hvcERpcnR5UmVxEIe2ARISCgxTaG9w",
            "RGlydHlSZXMQiLYBEhAKClNob3BCdXlSZXEQibYBEhAKClNob3BCdXlSZXMQ",
            "irYBEhUKD1Nob3BCdXlHYWNoYVJlcRCLtgESFQoPU2hvcEJ1eUdhY2hhUmVz",
            "EIy2ARITCg1IYW5nVXBJbmZvUmVxEOi2ARITCg1IYW5nVXBJbmZvUmVzEOm2",
            "ARISCgxIYW5nVXBHZXRSZXEQ6rYBEhIKDEhhbmdVcEdldFJlcxDrtgESFgoQ",
            "SGFuZ1VwRmFzdEdldFJlcRDstgESFgoQSGFuZ1VwRmFzdEdldFJlcxDttgES",
            "EwoNVGFsZW50SW5mb1JlcRDMtwESEwoNVGFsZW50SW5mb1JlcxDNtwESFQoP",
            "VGFsZW50VW5Mb2NrUmVxEM63ARIVCg9UYWxlbnRVbkxvY2tSZXMQz7cBEhAK",
            "ClBldEluZm9SZXEQsLgBEhAKClBldEluZm9SZXMQsbgBEhEKC1BldERpcnR5",
            "UmVxELK4ARIRCgtQZXREaXJ0eVJlcxCzuAESEwoNUGV0TGV2ZWxVcFJlcRC0",
            "uAESEwoNUGV0TGV2ZWxVcFJlcxC1uAESEgoMUGV0U3RhclVwUmVxELa4ARIS",
            "CgxQZXRTdGFyVXBSZXMQt7gBEhkKE1N5c3RlbVVuTG9ja0luZm9SZXEQlLkB",
            "EhkKE1N5c3RlbVVuTG9ja0luZm9SZXMQlbkBEhUKD1N5c3RlbVVuTG9ja1Jl",
            "cxCWuQESFQoPRXhjaGFuZ2VDb2RlUmVxEPi5ARIVCg9FeGNoYW5nZUNvZGVS",
            "ZXMQ+bkBEhMKDUNoYW5nZU5hbWVSZXEQ3LoBEhMKDUNoYW5nZU5hbWVSZXMQ",
            "3boBEhUKD1dlYkVtYWlsU2VuZFJlcRDAuwESFAoOV2ViRW1haWxEZWxSZXEQ",
            "wbsBEhIKDEVtYWlsSW5mb1JlcRCkvAESEgoMRW1haWxJbmZvUmVzEKW8ARIT",
            "Cg1FbWFpbERpcnR5UmVzEKa8ARIUCg5FbWFpbFJld2FyZFJlcRCnvAESFAoO",
            "RW1haWxSZXdhcmRSZXMQqLwBEhIKDEVtYWlsUmVhZFJlcRCpvAESEgoMRW1h",
            "aWxSZWFkUmVzEKq8ARIZChNTZXZlbkRheUdpZnRJbmZvUmVzEIzEARIcChZT",
            "ZXZlbkRheUdpZnRSZWNlaXZlUmVxEI3EARIcChZTZXZlbkRheUdpZnRSZWNl",
            "aXZlUmVzEI7EARIVChBSb29tRnJhbWVTdGVwUmVxELgXEhUKEFJvb21GcmFt",
            "ZVN0ZXBSZXMQuRcSFQoQUm9vbUZyYW1lUGluZ1JlcRC6FxIVChBSb29tRnJh",
            "bWVQaW5nUmVzELsXEhEKDEVudGVyUm9vbVJlcRC8FxIRCgxFbnRlclJvb21S",
            "ZXMQvRcSFwoSTm90aWZ5TWF0Y2hSb29tUmVzEL4XEhEKDExlYXZlUm9vbVJl",
            "cRC/FxIRCgxMZWF2ZVJvb21SZXMQwBcSFQoQTm90aWZ5QWRkUm9vbVJlcxDB",
            "FxIYChNSb29tQmF0dGxlU3RhdHVzUmVxEMIXEhgKE1Jvb21CYXR0bGVTdGF0",
            "dXNSZXMQwxcSHQoYTm90aWZ5Um9vbUJhdHRsZVN0YXJ0UmVzEMQXEhsKFk5v",
            "dGlmeVJvb21CYXR0bGVFbmRSZXMQxRdCHgoTY29tLnRvcGdhbWUubWVzc2Fn",
            "ZaoCBlByb3RvM2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto3.MID), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MID {
    [pbr::OriginalName("NONE")] None = 0,
    /// <summary>
    ///服务器内部消息
    /// </summary>
    [pbr::OriginalName("ServerRegisterReq")] ServerRegisterReq = 101,
    /// <summary>
    ///注册服务器消息
    /// </summary>
    [pbr::OriginalName("ServerRegisterRes")] ServerRegisterRes = 102,
    /// <summary>
    ///获取服务器列表
    /// </summary>
    [pbr::OriginalName("ServerListReq")] ServerListReq = 103,
    /// <summary>
    ///获取服务器列表
    /// </summary>
    [pbr::OriginalName("ServerListRes")] ServerListRes = 104,
    /// <summary>
    ///改变角色服务器
    /// </summary>
    [pbr::OriginalName("ChangeRoleServerReq")] ChangeRoleServerReq = 105,
    /// <summary>
    ///改变角色服务器
    /// </summary>
    [pbr::OriginalName("ChangeRoleServerRes")] ChangeRoleServerRes = 106,
    /// <summary>
    ///服务器事件
    /// </summary>
    [pbr::OriginalName("ServerEventReq")] ServerEventReq = 107,
    /// <summary>
    ///服务器事件
    /// </summary>
    [pbr::OriginalName("ServerEventRes")] ServerEventRes = 108,
    /// <summary>
    ///服务器状态 
    /// </summary>
    [pbr::OriginalName("ServerStatusRes")] ServerStatusRes = 109,
    /// <summary>
    ///服务器内部GM
    /// </summary>
    [pbr::OriginalName("ServerCmdReq")] ServerCmdReq = 110,
    /// <summary>
    ///用户跟换服务器
    /// </summary>
    [pbr::OriginalName("LinkServerChangeRes")] LinkServerChangeRes = 111,
    /// <summary>
    ///web gm指令
    /// </summary>
    [pbr::OriginalName("WebGmReq")] WebGmReq = 112,
    /// <summary>
    ///web gm指令
    /// </summary>
    [pbr::OriginalName("WebGmRes")] WebGmRes = 113,
    /// <summary>
    ///设置登入服热更
    /// </summary>
    [pbr::OriginalName("WebToggleHotReq")] WebToggleHotReq = 114,
    /// <summary>
    ///web 发送公告
    /// </summary>
    [pbr::OriginalName("WebSendNoticeReq")] WebSendNoticeReq = 115,
    /// <summary>
    ///客户端登录列表请求 
    /// </summary>
    [pbr::OriginalName("ServerLoginListReq")] ServerLoginListReq = 200,
    /// <summary>
    ///客户端登录列表请求 
    /// </summary>
    [pbr::OriginalName("ServerLoginListRes")] ServerLoginListRes = 201,
    /// <summary>
    ///系统错误
    /// </summary>
    [pbr::OriginalName("SystemErrorRes")] SystemErrorRes = 401,
    /// <summary>
    ///GM
    /// </summary>
    [pbr::OriginalName("CommandReq")] CommandReq = 501,
    /// <summary>
    ///FlagDirty
    /// </summary>
    [pbr::OriginalName("FlagDirtyRes")] FlagDirtyRes = 601,
    /// <summary>
    ///0点刷新
    /// </summary>
    [pbr::OriginalName("NewDayDirtyReq")] NewDayDirtyReq = 602,
    /// <summary>
    ///0点刷新
    /// </summary>
    [pbr::OriginalName("NewDayDirtyRes")] NewDayDirtyRes = 603,
    /// <summary>
    ///日志操作
    /// </summary>
    [pbr::OriginalName("LogActionReq")] LogActionReq = 700,
    /// <summary>
    ///日志操作
    /// </summary>
    [pbr::OriginalName("LogActionBatchReq")] LogActionBatchReq = 701,
    /// <summary>
    ///踢出
    /// </summary>
    [pbr::OriginalName("KickOutRes")] KickOutRes = 10000,
    /// <summary>
    ///登录
    /// </summary>
    [pbr::OriginalName("LoginReq")] LoginReq = 10001,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("LoginRes")] LoginRes = 10002,
    /// <summary>
    ///心跳
    /// </summary>
    [pbr::OriginalName("HeartReq")] HeartReq = 10011,
    /// <summary>
    ///心跳
    /// </summary>
    [pbr::OriginalName("HeartRes")] HeartRes = 10012,
    /// <summary>
    ///玩家被踢下线
    /// </summary>
    [pbr::OriginalName("KillUserRes")] KillUserRes = 10013,
    /// <summary>
    /// 消息种子
    /// </summary>
    [pbr::OriginalName("MessageSeedRes")] MessageSeedRes = 10014,
    /// <summary>
    /// 登陆完成
    /// </summary>
    [pbr::OriginalName("LoginFinishRes")] LoginFinishRes = 10015,
    [pbr::OriginalName("LogoutReq")] LogoutReq = 10016,
    [pbr::OriginalName("LogoutRes")] LogoutRes = 10017,
    /// <summary>
    ///登录验证
    /// </summary>
    [pbr::OriginalName("LoginVerifyReq")] LoginVerifyReq = 10018,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("LoginVerifyRes")] LoginVerifyRes = 10019,
    /// <summary>
    ///用户基础信息
    /// </summary>
    [pbr::OriginalName("UserBaseInfoRes")] UserBaseInfoRes = 10020,
    /// <summary>
    ///保存引导数据
    /// </summary>
    [pbr::OriginalName("GuideSaveReq")] GuideSaveReq = 10021,
    /// <summary>
    ///引导数据信息
    /// </summary>
    [pbr::OriginalName("GuideInfoRes")] GuideInfoRes = 10022,
    /// <summary>
    ///支付生成订单
    /// </summary>
    [pbr::OriginalName("PayOrderGenReq")] PayOrderGenReq = 10100,
    [pbr::OriginalName("PayOrderGenRes")] PayOrderGenRes = 10101,
    /// <summary>
    ///支付订单状态
    /// </summary>
    [pbr::OriginalName("PaySdkActionReq")] PaySdkActionReq = 10102,
    [pbr::OriginalName("PaySdkActionRes")] PaySdkActionRes = 10103,
    /// <summary>
    ///SDK 支付回调
    /// </summary>
    [pbr::OriginalName("PaySdkCallbackRes")] PaySdkCallbackRes = 10104,
    /// <summary>
    ///请求进入关卡
    /// </summary>
    [pbr::OriginalName("EnterLevelReq")] EnterLevelReq = 20001,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EnterLevelRes")] EnterLevelRes = 20002,
    /// <summary>
    ///请求推出关卡
    /// </summary>
    [pbr::OriginalName("ExitLevelReq")] ExitLevelReq = 20011,
    [pbr::OriginalName("ExitLevelRes")] ExitLevelRes = 20012,
    /// <summary>
    ///请求开始
    /// </summary>
    [pbr::OriginalName("StartLevelReq")] StartLevelReq = 20013,
    [pbr::OriginalName("StartLevelRes")] StartLevelRes = 20014,
    /// <summary>
    ///请求复活
    /// </summary>
    [pbr::OriginalName("RevivePlayerReq")] RevivePlayerReq = 20015,
    [pbr::OriginalName("RevivePlayerRes")] RevivePlayerRes = 20016,
    /// <summary>
    ///挑战次数
    /// </summary>
    [pbr::OriginalName("ChallengesRes")] ChallengesRes = 20017,
    /// <summary>
    ///挑战关卡信息
    /// </summary>
    [pbr::OriginalName("ChallengesDirtyRes")] ChallengesDirtyRes = 20018,
    [pbr::OriginalName("AddChallengesLevelRes")] AddChallengesLevelRes = 20019,
    [pbr::OriginalName("AchieveInfoRes")] AchieveInfoRes = 21000,
    [pbr::OriginalName("AchieveDirtyRes")] AchieveDirtyRes = 21001,
    /// <summary>
    ///成就奖励
    /// </summary>
    [pbr::OriginalName("AchieveRewardReq")] AchieveRewardReq = 21002,
    [pbr::OriginalName("AchieveRewardRes")] AchieveRewardRes = 21003,
    /// <summary>
    ///排行榜信息
    /// </summary>
    [pbr::OriginalName("RankInfoReq")] RankInfoReq = 22000,
    [pbr::OriginalName("RankInfoRes")] RankInfoRes = 22001,
    /// <summary>
    ///获取某个用户位置的前后排名
    /// </summary>
    [pbr::OriginalName("RankUserReq")] RankUserReq = 22002,
    [pbr::OriginalName("RankUserRes")] RankUserRes = 22003,
    /// <summary>
    ///排名变化
    /// </summary>
    [pbr::OriginalName("DirtyRankRes")] DirtyRankRes = 22004,
    /// <summary>
    ///排名奖励
    /// </summary>
    [pbr::OriginalName("RankRewardReq")] RankRewardReq = 22005,
    /// <summary>
    ///排名奖励
    /// </summary>
    [pbr::OriginalName("RankRewardRes")] RankRewardRes = 22006,
    /// <summary>
    ///英雄信息
    /// </summary>
    [pbr::OriginalName("HeroInfoRes")] HeroInfoRes = 23000,
    /// <summary>
    ///出战英雄修改
    /// </summary>
    [pbr::OriginalName("HeroFightChangeReq")] HeroFightChangeReq = 23001,
    [pbr::OriginalName("HeroFightChangeRes")] HeroFightChangeRes = 23002,
    /// <summary>
    ///购买英雄
    /// </summary>
    [pbr::OriginalName("HeroBuyReq")] HeroBuyReq = 23003,
    [pbr::OriginalName("HeroBuyRes")] HeroBuyRes = 23004,
    /// <summary>
    ///英雄装备
    /// </summary>
    [pbr::OriginalName("HeroEquipReq")] HeroEquipReq = 23005,
    [pbr::OriginalName("HeroEquipRes")] HeroEquipRes = 23006,
    [pbr::OriginalName("HeroDirtyRes")] HeroDirtyRes = 23007,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EquipInfosRes")] EquipInfosRes = 23008,
    /// <summary>
    ///道具变化
    /// </summary>
    [pbr::OriginalName("EquipDirtyReq")] EquipDirtyReq = 23009,
    /// <summary>
    ///道具变化
    /// </summary>
    [pbr::OriginalName("EquipDirtyRes")] EquipDirtyRes = 23010,
    /// <summary>
    ///英雄装备解锁
    /// </summary>
    [pbr::OriginalName("HeroEquipUnlockReq")] HeroEquipUnlockReq = 23011,
    [pbr::OriginalName("HeroEquipUnlockRes")] HeroEquipUnlockRes = 23012,
    /// <summary>
    ///英雄装备升级
    /// </summary>
    [pbr::OriginalName("HeroEquipUpgradeReq")] HeroEquipUpgradeReq = 23013,
    [pbr::OriginalName("HeroEquipUpgradeRes")] HeroEquipUpgradeRes = 23014,
    /// <summary>
    ///道具信息
    /// </summary>
    [pbr::OriginalName("ItemInfosRes")] ItemInfosRes = 23100,
    /// <summary>
    ///道具变化
    /// </summary>
    [pbr::OriginalName("ItemDirtyReq")] ItemDirtyReq = 23101,
    /// <summary>
    ///道具变化
    /// </summary>
    [pbr::OriginalName("ItemDirtyRes")] ItemDirtyRes = 23102,
    /// <summary>
    ///开宝箱
    /// </summary>
    [pbr::OriginalName("OpenChestReq")] OpenChestReq = 23103,
    [pbr::OriginalName("OpenChestRes")] OpenChestRes = 23104,
    /// <summary>
    ///购买体力
    /// </summary>
    [pbr::OriginalName("BuyActionPointReq")] BuyActionPointReq = 23105,
    /// <summary>
    ///购买体力
    /// </summary>
    [pbr::OriginalName("BuyActionPointRes")] BuyActionPointRes = 23106,
    /// <summary>
    ///签到
    /// </summary>
    [pbr::OriginalName("SignInReq")] SignInReq = 23200,
    [pbr::OriginalName("SignInRes")] SignInRes = 23201,
    /// <summary>
    ///商店
    /// </summary>
    [pbr::OriginalName("ShopInfoReq")] ShopInfoReq = 23301,
    [pbr::OriginalName("ShopInfoRes")] ShopInfoRes = 23302,
    [pbr::OriginalName("ShopDirtyReq")] ShopDirtyReq = 23303,
    [pbr::OriginalName("ShopDirtyRes")] ShopDirtyRes = 23304,
    [pbr::OriginalName("ShopBuyReq")] ShopBuyReq = 23305,
    [pbr::OriginalName("ShopBuyRes")] ShopBuyRes = 23306,
    [pbr::OriginalName("ShopBuyGachaReq")] ShopBuyGachaReq = 23307,
    [pbr::OriginalName("ShopBuyGachaRes")] ShopBuyGachaRes = 23308,
    /// <summary>
    ///挂机
    /// </summary>
    [pbr::OriginalName("HangUpInfoReq")] HangUpInfoReq = 23400,
    [pbr::OriginalName("HangUpInfoRes")] HangUpInfoRes = 23401,
    [pbr::OriginalName("HangUpGetReq")] HangUpGetReq = 23402,
    [pbr::OriginalName("HangUpGetRes")] HangUpGetRes = 23403,
    [pbr::OriginalName("HangUpFastGetReq")] HangUpFastGetReq = 23404,
    [pbr::OriginalName("HangUpFastGetRes")] HangUpFastGetRes = 23405,
    /// <summary>
    ///天赋
    /// </summary>
    [pbr::OriginalName("TalentInfoReq")] TalentInfoReq = 23500,
    [pbr::OriginalName("TalentInfoRes")] TalentInfoRes = 23501,
    [pbr::OriginalName("TalentUnLockReq")] TalentUnLockReq = 23502,
    [pbr::OriginalName("TalentUnLockRes")] TalentUnLockRes = 23503,
    /// <summary>
    ///宠物
    /// </summary>
    [pbr::OriginalName("PetInfoReq")] PetInfoReq = 23600,
    [pbr::OriginalName("PetInfoRes")] PetInfoRes = 23601,
    /// <summary>
    ///宠物变化
    /// </summary>
    [pbr::OriginalName("PetDirtyReq")] PetDirtyReq = 23602,
    [pbr::OriginalName("PetDirtyRes")] PetDirtyRes = 23603,
    [pbr::OriginalName("PetLevelUpReq")] PetLevelUpReq = 23604,
    [pbr::OriginalName("PetLevelUpRes")] PetLevelUpRes = 23605,
    [pbr::OriginalName("PetStarUpReq")] PetStarUpReq = 23606,
    [pbr::OriginalName("PetStarUpRes")] PetStarUpRes = 23607,
    /// <summary>
    ///功能解锁
    /// </summary>
    [pbr::OriginalName("SystemUnLockInfoReq")] SystemUnLockInfoReq = 23700,
    [pbr::OriginalName("SystemUnLockInfoRes")] SystemUnLockInfoRes = 23701,
    [pbr::OriginalName("SystemUnLockRes")] SystemUnLockRes = 23702,
    /// <summary>
    ///兑换码
    /// </summary>
    [pbr::OriginalName("ExchangeCodeReq")] ExchangeCodeReq = 23800,
    [pbr::OriginalName("ExchangeCodeRes")] ExchangeCodeRes = 23801,
    /// <summary>
    ///改名
    /// </summary>
    [pbr::OriginalName("ChangeNameReq")] ChangeNameReq = 23900,
    [pbr::OriginalName("ChangeNameRes")] ChangeNameRes = 23901,
    /// <summary>
    ///web邮件
    /// </summary>
    [pbr::OriginalName("WebEmailSendReq")] WebEmailSendReq = 24000,
    [pbr::OriginalName("WebEmailDelReq")] WebEmailDelReq = 24001,
    /// <summary>
    ///邮件
    /// </summary>
    [pbr::OriginalName("EmailInfoReq")] EmailInfoReq = 24100,
    [pbr::OriginalName("EmailInfoRes")] EmailInfoRes = 24101,
    [pbr::OriginalName("EmailDirtyRes")] EmailDirtyRes = 24102,
    [pbr::OriginalName("EmailRewardReq")] EmailRewardReq = 24103,
    [pbr::OriginalName("EmailRewardRes")] EmailRewardRes = 24104,
    [pbr::OriginalName("EmailReadReq")] EmailReadReq = 24105,
    [pbr::OriginalName("EmailReadRes")] EmailReadRes = 24106,
    /// <summary>
    ///七日礼包
    /// </summary>
    [pbr::OriginalName("SevenDayGiftInfoRes")] SevenDayGiftInfoRes = 25100,
    [pbr::OriginalName("SevenDayGiftReceiveReq")] SevenDayGiftReceiveReq = 25101,
    [pbr::OriginalName("SevenDayGiftReceiveRes")] SevenDayGiftReceiveRes = 25102,
    /// <summary>
    ///帧同步
    /// </summary>
    [pbr::OriginalName("RoomFrameStepReq")] RoomFrameStepReq = 3000,
    /// <summary>
    ///帧同步
    /// </summary>
    [pbr::OriginalName("RoomFrameStepRes")] RoomFrameStepRes = 3001,
    /// <summary>
    ///离开房间
    /// </summary>
    [pbr::OriginalName("RoomFramePingReq")] RoomFramePingReq = 3002,
    /// <summary>
    ///	
    /// </summary>
    [pbr::OriginalName("RoomFramePingRes")] RoomFramePingRes = 3003,
    /// <summary>
    ///加入房间
    /// </summary>
    [pbr::OriginalName("EnterRoomReq")] EnterRoomReq = 3004,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EnterRoomRes")] EnterRoomRes = 3005,
    [pbr::OriginalName("NotifyMatchRoomRes")] NotifyMatchRoomRes = 3006,
    /// <summary>
    ///离开房间
    /// </summary>
    [pbr::OriginalName("LeaveRoomReq")] LeaveRoomReq = 3007,
    /// <summary>
    ///	
    /// </summary>
    [pbr::OriginalName("LeaveRoomRes")] LeaveRoomRes = 3008,
    /// <summary>
    ///通知有人加入房间	
    /// </summary>
    [pbr::OriginalName("NotifyAddRoomRes")] NotifyAddRoomRes = 3009,
    /// <summary>
    ///房间战斗状态
    /// </summary>
    [pbr::OriginalName("RoomBattleStatusReq")] RoomBattleStatusReq = 3010,
    [pbr::OriginalName("RoomBattleStatusRes")] RoomBattleStatusRes = 3011,
    [pbr::OriginalName("NotifyRoomBattleStartRes")] NotifyRoomBattleStartRes = 3012,
    [pbr::OriginalName("NotifyRoomBattleEndRes")] NotifyRoomBattleEndRes = 3013,
  }

  #endregion

}

#endregion Designer generated code
